INFO 2023-08-30 19:03:10,273 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-30 19:03:18,670 basehttp 161 "GET / HTTP/1.1" 200 10697
INFO 2023-08-30 19:15:36,482 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-30 19:16:08,528 basehttp 161 "GET / HTTP/1.1" 200 10697
INFO 2023-08-30 19:16:42,706 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\meiduo_mall\settings.py changed, reloading.
INFO 2023-08-30 19:16:43,501 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-30 21:39:57,805 basehttp 161 "GET / HTTP/1.1" 200 10697
INFO 2023-08-30 22:38:06,377 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-30 22:40:40,074 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\meiduo_mall\settings.py changed, reloading.
INFO 2023-08-30 22:40:40,568 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-30 22:41:53,210 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-30 22:45:22,661 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-30 22:45:42,557 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\apps.py changed, reloading.
INFO 2023-08-30 22:45:43,042 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-30 22:46:21,741 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-30 22:46:35,554 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-30 22:46:48,328 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-30 22:47:11,986 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\models.py changed, reloading.
INFO 2023-08-30 22:47:12,671 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-30 22:53:58,757 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\apps.py changed, reloading.
INFO 2023-08-30 22:53:59,339 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-30 22:56:36,184 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-30 23:04:28,742 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-30 23:04:39,413 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\apps.py changed, reloading.
INFO 2023-08-30 23:04:40,073 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-30 23:07:33,165 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-30 23:09:26,510 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\apps.py changed, reloading.
INFO 2023-08-30 23:09:27,081 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-30 23:10:15,993 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-30 23:36:37,943 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-30 23:36:40,395 basehttp 161 "GET / HTTP/1.1" 200 10697
INFO 2023-08-31 09:38:57,424 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 09:40:46,297 autoreload 636 Watching for file changes with StatReloader
WARNING 2023-08-31 09:41:20,585 log 224 Not Found: /username/daguo/count/
WARNING 2023-08-31 09:41:20,586 basehttp 161 "GET /username/daguo/count/ HTTP/1.1" 404 2131
INFO 2023-08-31 09:41:52,540 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 09:42:05,445 autoreload 636 Watching for file changes with StatReloader
WARNING 2023-08-31 09:42:08,448 log 224 Not Found: /username/daguo/count/
WARNING 2023-08-31 09:42:08,448 basehttp 161 "GET /username/daguo/count/ HTTP/1.1" 404 2211
WARNING 2023-08-31 09:42:34,049 log 224 Not Found: /usernames/user/count/
WARNING 2023-08-31 09:42:34,049 basehttp 161 "GET /usernames/user/count/ HTTP/1.1" 404 2211
INFO 2023-08-31 09:42:56,629 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 09:42:59,991 basehttp 161 "GET /usernames/user/count/ HTTP/1.1" 200 39
INFO 2023-08-31 09:48:45,346 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2023-08-31 09:48:45,918 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 09:48:54,327 basehttp 161 "GET /usernames/user/count/ HTTP/1.1" 200 75
INFO 2023-08-31 09:54:39,681 autoreload 636 Watching for file changes with StatReloader
WARNING 2023-08-31 09:54:44,858 log 224 Not Found: /usernames/user/count/
WARNING 2023-08-31 09:54:44,859 basehttp 161 "GET /usernames/user/count/ HTTP/1.1" 404 2219
INFO 2023-08-31 10:09:52,652 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\meiduo_mall\settings.py changed, reloading.
INFO 2023-08-31 10:09:53,190 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 10:11:00,322 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\meiduo_mall\settings.py changed, reloading.
INFO 2023-08-31 10:11:00,881 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 10:12:11,047 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\meiduo_mall\settings.py changed, reloading.
INFO 2023-08-31 10:12:11,622 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 10:13:05,360 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\meiduo_mall\settings.py changed, reloading.
INFO 2023-08-31 10:13:05,941 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 10:16:38,313 autoreload 636 Watching for file changes with StatReloader
WARNING 2023-08-31 10:20:44,145 log 224 Not Found: /usernames/daguo/count/
WARNING 2023-08-31 10:20:44,146 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 404 2222
INFO 2023-08-31 10:21:06,750 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\meiduo_mall\settings.py changed, reloading.
INFO 2023-08-31 10:21:07,386 autoreload 636 Watching for file changes with StatReloader
WARNING 2023-08-31 10:21:08,936 log 224 Not Found: /usernames/daguo/count/
WARNING 2023-08-31 10:21:08,936 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 404 2222
WARNING 2023-08-31 10:21:16,020 log 224 Not Found: /usernames/daguo2/count/
WARNING 2023-08-31 10:21:16,020 basehttp 161 "GET /usernames/daguo2/count/ HTTP/1.1" 404 2225
WARNING 2023-08-31 10:21:43,270 log 224 Not Found: /username/daguo/count/
WARNING 2023-08-31 10:21:43,271 basehttp 161 "GET /username/daguo/count/ HTTP/1.1" 404 2219
WARNING 2023-08-31 10:23:38,901 log 224 Not Found: /username/daguo/count/
WARNING 2023-08-31 10:23:38,902 basehttp 161 "GET /username/daguo/count/ HTTP/1.1" 404 2219
INFO 2023-08-31 10:23:44,046 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\urls.py changed, reloading.
INFO 2023-08-31 10:23:44,653 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 10:23:58,222 autoreload 636 Watching for file changes with StatReloader
WARNING 2023-08-31 10:24:01,526 log 224 Not Found: /username/daguo/count/
WARNING 2023-08-31 10:24:01,527 basehttp 161 "GET /username/daguo/count/ HTTP/1.1" 404 2210
INFO 2023-08-31 10:24:22,424 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\meiduo_mall\settings.py changed, reloading.
INFO 2023-08-31 10:24:23,053 autoreload 636 Watching for file changes with StatReloader
WARNING 2023-08-31 10:24:24,703 log 224 Not Found: /username/daguo/count/
WARNING 2023-08-31 10:24:24,704 basehttp 161 "GET /username/daguo/count/ HTTP/1.1" 404 2210
WARNING 2023-08-31 10:24:33,614 log 224 Not Found: /username/daguo2/count/
WARNING 2023-08-31 10:24:33,615 basehttp 161 "GET /username/daguo2/count/ HTTP/1.1" 404 2213
INFO 2023-08-31 10:24:56,430 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2023-08-31 10:24:57,017 autoreload 636 Watching for file changes with StatReloader
WARNING 2023-08-31 10:24:59,627 log 224 Not Found: /username/daguo2/count/
WARNING 2023-08-31 10:24:59,627 basehttp 161 "GET /username/daguo2/count/ HTTP/1.1" 404 2213
WARNING 2023-08-31 10:25:02,575 log 224 Not Found: /username/dagu/count/
WARNING 2023-08-31 10:25:02,576 basehttp 161 "GET /username/dagu/count/ HTTP/1.1" 404 2207
WARNING 2023-08-31 10:25:42,648 log 224 Not Found: /
WARNING 2023-08-31 10:25:42,649 basehttp 161 "GET / HTTP/1.1" 404 2129
INFO 2023-08-31 10:25:42,680 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\meiduo_mall\settings.py changed, reloading.
INFO 2023-08-31 10:25:43,317 autoreload 636 Watching for file changes with StatReloader
WARNING 2023-08-31 10:25:43,598 log 224 Not Found: /favicon.ico
WARNING 2023-08-31 10:25:43,598 basehttp 161 "GET /favicon.ico HTTP/1.1" 404 2180
INFO 2023-08-31 10:26:05,813 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 200 39
WARNING 2023-08-31 10:26:21,727 log 224 Not Found: /username/dagu0/count/
WARNING 2023-08-31 10:26:21,727 basehttp 161 "GET /username/dagu0/count/ HTTP/1.1" 404 2210
INFO 2023-08-31 10:26:53,341 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 200 39
INFO 2023-08-31 10:27:01,223 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 200 39
INFO 2023-08-31 10:27:12,101 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2023-08-31 10:27:12,674 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 10:27:20,219 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\urls.py changed, reloading.
INFO 2023-08-31 10:27:20,759 autoreload 636 Watching for file changes with StatReloader
WARNING 2023-08-31 10:27:24,622 log 224 Not Found: /usernames/daguo/count/
WARNING 2023-08-31 10:27:24,624 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 404 2222
WARNING 2023-08-31 10:27:28,041 log 224 Not Found: /usernames/daguo/count/
WARNING 2023-08-31 10:27:28,041 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 404 2222
INFO 2023-08-31 10:28:31,241 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\utils\converters.py changed, reloading.
INFO 2023-08-31 10:28:31,848 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 10:28:35,206 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 200 39
INFO 2023-08-31 10:28:43,302 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 200 39
WARNING 2023-08-31 10:28:47,400 log 224 Not Found: /usernames/dago/count/
WARNING 2023-08-31 10:28:47,401 basehttp 161 "GET /usernames/dago/count/ HTTP/1.1" 404 2219
INFO 2023-08-31 10:28:52,293 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 200 39
INFO 2023-08-31 10:29:22,696 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2023-08-31 10:29:23,232 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 10:35:49,601 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\meiduo_mall\settings.py changed, reloading.
INFO 2023-08-31 10:35:50,171 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 10:44:29,619 autoreload 636 Watching for file changes with StatReloader
WARNING 2023-08-31 10:44:36,866 log 224 Not Found: /image_codes/bea83738-fdb0-425c-8a0c-e44aa411bbce/
WARNING 2023-08-31 10:44:36,866 basehttp 161 "GET /image_codes/bea83738-fdb0-425c-8a0c-e44aa411bbce/ HTTP/1.1" 404 2309
WARNING 2023-08-31 10:45:26,486 log 224 Not Found: /
WARNING 2023-08-31 10:45:26,487 basehttp 161 "GET / HTTP/1.1" 404 2144
WARNING 2023-08-31 10:45:26,620 log 224 Not Found: /favicon.ico
WARNING 2023-08-31 10:45:26,621 basehttp 161 "GET /favicon.ico HTTP/1.1" 404 2195
INFO 2023-08-31 10:46:01,688 autoreload 636 Watching for file changes with StatReloader
WARNING 2023-08-31 10:48:55,732 log 224 Not Found: /carts/simple/
WARNING 2023-08-31 10:48:55,732 basehttp 161 "GET /carts/simple/ HTTP/1.1" 404 2201
WARNING 2023-08-31 10:49:07,271 log 224 Not Found: /image_codes/e4466bf4-08be-4efd-94c0-8ca85963344f/
WARNING 2023-08-31 10:49:07,273 basehttp 161 "GET /image_codes/e4466bf4-08be-4efd-94c0-8ca85963344f/ HTTP/1.1" 404 2309
WARNING 2023-08-31 10:49:59,042 log 224 Not Found: /image_codes/15bcd242-73fe-4a3e-8526-40c9c9086318/
WARNING 2023-08-31 10:49:59,042 basehttp 161 "GET /image_codes/15bcd242-73fe-4a3e-8526-40c9c9086318/ HTTP/1.1" 404 2309
INFO 2023-08-31 10:50:16,099 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 200 39
INFO 2023-08-31 10:50:52,564 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\meiduo_mall\settings.py changed, reloading.
INFO 2023-08-31 10:50:53,157 autoreload 636 Watching for file changes with StatReloader
WARNING 2023-08-31 10:50:55,427 log 224 Not Found: /image_codes/25ef87c1-1115-498e-9e19-7d63d5cca630/
WARNING 2023-08-31 10:50:55,428 basehttp 161 "GET /image_codes/25ef87c1-1115-498e-9e19-7d63d5cca630/ HTTP/1.1" 404 2309
INFO 2023-08-31 10:50:59,117 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 200 39
INFO 2023-08-31 10:51:02,322 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 200 39
INFO 2023-08-31 10:51:28,335 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 10:51:32,785 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 200 39
WARNING 2023-08-31 10:51:33,226 log 224 Not Found: /carts/simple/
WARNING 2023-08-31 10:51:33,227 basehttp 161 "GET /carts/simple/ HTTP/1.1" 404 2201
WARNING 2023-08-31 10:51:38,360 log 224 Not Found: /image_codes/3a3ddcdc-29f9-4059-8cc1-a10e5b0e8c4f/
WARNING 2023-08-31 10:51:38,360 basehttp 161 "GET /image_codes/3a3ddcdc-29f9-4059-8cc1-a10e5b0e8c4f/ HTTP/1.1" 404 2309
INFO 2023-08-31 10:51:47,883 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 200 39
INFO 2023-08-31 10:51:50,344 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 200 39
INFO 2023-08-31 10:51:51,922 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 200 39
INFO 2023-08-31 10:51:53,026 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 200 39
INFO 2023-08-31 10:51:53,946 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 200 39
INFO 2023-08-31 10:51:54,769 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 200 39
INFO 2023-08-31 10:51:55,036 basehttp 161 "GET /usernames/daguo/count/ HTTP/1.1" 200 39
INFO 2023-08-31 11:06:09,860 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 11:06:12,773 basehttp 161 "GET /mobiles/13856541252/count/ HTTP/1.1" 200 39
WARNING 2023-08-31 11:06:20,167 log 224 Not Found: /mobiles/1385654122/count/
WARNING 2023-08-31 11:06:20,168 basehttp 161 "GET /mobiles/1385654122/count/ HTTP/1.1" 404 2414
INFO 2023-08-31 15:07:12,616 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 15:08:28,982 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\meiduo_mall\settings.py changed, reloading.
INFO 2023-08-31 15:08:29,541 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 15:08:37,645 basehttp 161 "POST /register/ HTTP/1.1" 200 51
INFO 2023-08-31 15:09:07,120 basehttp 161 "POST /register/ HTTP/1.1" 200 51
INFO 2023-08-31 15:09:12,817 basehttp 161 "POST /register/ HTTP/1.1" 200 51
INFO 2023-08-31 15:09:44,431 basehttp 161 "POST /register/ HTTP/1.1" 200 75
INFO 2023-08-31 15:09:53,053 basehttp 161 "POST /register/ HTTP/1.1" 200 69
INFO 2023-08-31 15:10:02,255 basehttp 161 "POST /register/ HTTP/1.1" 200 69
INFO 2023-08-31 15:10:11,923 basehttp 161 "POST /register/ HTTP/1.1" 200 75
INFO 2023-08-31 15:10:20,656 basehttp 161 "POST /register/ HTTP/1.1" 200 75
INFO 2023-08-31 15:10:43,585 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2023-08-31 15:10:44,163 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 15:10:52,969 basehttp 161 "POST /register/ HTTP/1.1" 200 75
INFO 2023-08-31 15:10:58,640 basehttp 161 "POST /register/ HTTP/1.1" 200 75
INFO 2023-08-31 15:11:45,294 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2023-08-31 15:11:45,832 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 15:11:50,188 basehttp 161 "POST /register/ HTTP/1.1" 200 27
INFO 2023-08-31 15:14:03,891 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2023-08-31 15:14:04,567 autoreload 636 Watching for file changes with StatReloader
ERROR 2023-08-31 15:14:06,572 log 224 Internal Server Error: /register/
Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python310\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python310\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "D:\Python310\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "D:\Python310\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1062, "Duplicate entry 'daguo' for key 'tb_users.username'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\PythonProject\meiduo_project\meiduo_mall\apps\users\views.py", line 66, in post
    User.objects.create(username=username, password=password, mobile=mobile)
  File "D:\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python310\lib\site-packages\django\db\models\query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\Python310\lib\site-packages\django\contrib\auth\base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "D:\Python310\lib\site-packages\django\db\models\base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "D:\Python310\lib\site-packages\django\db\models\base.py", line 763, in save_base
    updated = self._save_table(
  File "D:\Python310\lib\site-packages\django\db\models\base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "D:\Python310\lib\site-packages\django\db\models\base.py", line 906, in _do_insert
    return manager._insert(
  File "D:\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python310\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1410, in execute_sql
    cursor.execute(sql, params)
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "D:\Python310\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python310\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python310\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "D:\Python310\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "D:\Python310\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry 'daguo' for key 'tb_users.username'")
ERROR 2023-08-31 15:14:06,579 basehttp 161 "POST /register/ HTTP/1.1" 500 196112
INFO 2023-08-31 15:16:49,056 basehttp 161 "POST /register/ HTTP/1.1" 200 27
INFO 2023-08-31 15:17:04,908 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 15:17:30,179 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 15:17:45,302 basehttp 161 "POST /register/ HTTP/1.1" 200 27
INFO 2023-08-31 15:18:37,430 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2023-08-31 15:18:37,996 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 15:18:53,904 basehttp 161 "POST /register/ HTTP/1.1" 200 27
INFO 2023-08-31 15:19:38,027 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2023-08-31 15:19:38,593 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 15:19:40,624 basehttp 161 "POST /register/ HTTP/1.1" 200 81
ERROR 2023-08-31 15:19:50,418 log 224 Internal Server Error: /register/
Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python310\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python310\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "D:\Python310\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "D:\Python310\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1062, "Duplicate entry 'daguo' for key 'tb_users.username'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\PythonProject\meiduo_project\meiduo_mall\apps\users\views.py", line 66, in post
    User.objects.create(username=username, password=password, mobile=mobile)
  File "D:\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python310\lib\site-packages\django\db\models\query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\Python310\lib\site-packages\django\contrib\auth\base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "D:\Python310\lib\site-packages\django\db\models\base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "D:\Python310\lib\site-packages\django\db\models\base.py", line 763, in save_base
    updated = self._save_table(
  File "D:\Python310\lib\site-packages\django\db\models\base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "D:\Python310\lib\site-packages\django\db\models\base.py", line 906, in _do_insert
    return manager._insert(
  File "D:\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python310\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1410, in execute_sql
    cursor.execute(sql, params)
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "D:\Python310\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python310\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python310\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "D:\Python310\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "D:\Python310\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry 'daguo' for key 'tb_users.username'")
ERROR 2023-08-31 15:19:50,429 basehttp 161 "POST /register/ HTTP/1.1" 500 196119
INFO 2023-08-31 15:23:56,878 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2023-08-31 15:23:57,452 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 15:23:59,819 basehttp 161 "POST /register/ HTTP/1.1" 200 51
INFO 2023-08-31 15:24:21,108 basehttp 161 "POST /register/ HTTP/1.1" 200 27
INFO 2023-08-31 15:24:32,845 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2023-08-31 15:24:33,453 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 15:24:33,722 basehttp 161 "POST /register/ HTTP/1.1" 200 81
INFO 2023-08-31 15:24:46,197 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2023-08-31 15:24:46,785 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 15:24:49,394 basehttp 161 "POST /register/ HTTP/1.1" 200 27
INFO 2023-08-31 15:24:55,692 basehttp 161 "POST /register/ HTTP/1.1" 200 51
INFO 2023-08-31 15:25:34,533 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2023-08-31 15:25:35,163 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 15:25:35,890 basehttp 161 "POST /register/ HTTP/1.1" 200 51
INFO 2023-08-31 15:26:04,309 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2023-08-31 15:26:04,916 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 15:26:06,358 basehttp 161 "POST /register/ HTTP/1.1" 200 81
INFO 2023-08-31 15:29:47,340 autoreload 636 Watching for file changes with StatReloader
ERROR 2023-08-31 15:29:59,880 log 224 Internal Server Error: /register/
Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python310\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python310\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "D:\Python310\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "D:\Python310\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1062, "Duplicate entry 'daguo' for key 'tb_users.username'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\PythonProject\meiduo_project\meiduo_mall\apps\users\views.py", line 69, in post
    User.objects.create_user(username=username, password=password, mobile=mobile)
  File "D:\Python310\lib\site-packages\django\contrib\auth\models.py", line 152, in create_user
    return self._create_user(username, email, password, **extra_fields)
  File "D:\Python310\lib\site-packages\django\contrib\auth\models.py", line 146, in _create_user
    user.save(using=self._db)
  File "D:\Python310\lib\site-packages\django\contrib\auth\base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "D:\Python310\lib\site-packages\django\db\models\base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "D:\Python310\lib\site-packages\django\db\models\base.py", line 763, in save_base
    updated = self._save_table(
  File "D:\Python310\lib\site-packages\django\db\models\base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "D:\Python310\lib\site-packages\django\db\models\base.py", line 906, in _do_insert
    return manager._insert(
  File "D:\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python310\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1410, in execute_sql
    cursor.execute(sql, params)
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "D:\Python310\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python310\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python310\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "D:\Python310\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "D:\Python310\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry 'daguo' for key 'tb_users.username'")
ERROR 2023-08-31 15:29:59,887 basehttp 161 "POST /register/ HTTP/1.1" 500 198760
ERROR 2023-08-31 15:30:41,296 log 224 Internal Server Error: /register/
Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python310\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python310\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "D:\Python310\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "D:\Python310\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1062, "Duplicate entry 'daguo' for key 'tb_users.username'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\PythonProject\meiduo_project\meiduo_mall\apps\users\views.py", line 69, in post
    User.objects.create_user(username=username, password=password, mobile=mobile)
  File "D:\Python310\lib\site-packages\django\contrib\auth\models.py", line 152, in create_user
    return self._create_user(username, email, password, **extra_fields)
  File "D:\Python310\lib\site-packages\django\contrib\auth\models.py", line 146, in _create_user
    user.save(using=self._db)
  File "D:\Python310\lib\site-packages\django\contrib\auth\base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "D:\Python310\lib\site-packages\django\db\models\base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "D:\Python310\lib\site-packages\django\db\models\base.py", line 763, in save_base
    updated = self._save_table(
  File "D:\Python310\lib\site-packages\django\db\models\base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "D:\Python310\lib\site-packages\django\db\models\base.py", line 906, in _do_insert
    return manager._insert(
  File "D:\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python310\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1410, in execute_sql
    cursor.execute(sql, params)
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "D:\Python310\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python310\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python310\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python310\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "D:\Python310\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "D:\Python310\lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry 'daguo' for key 'tb_users.username'")
ERROR 2023-08-31 15:30:41,314 basehttp 161 "POST /register/ HTTP/1.1" 500 198760
INFO 2023-08-31 15:31:19,882 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 15:31:26,387 autoreload 250 E:\PythonProject\meiduo_project\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2023-08-31 15:31:27,021 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 15:31:29,675 basehttp 161 "POST /register/ HTTP/1.1" 200 27
INFO 2023-08-31 15:40:23,543 basehttp 161 "GET /usernames/daguo01/count/ HTTP/1.1" 200 39
INFO 2023-08-31 15:40:42,201 basehttp 161 "GET /mobiles/18211111111/count/ HTTP/1.1" 200 39
INFO 2023-08-31 15:40:49,212 basehttp 161 "OPTIONS /register/ HTTP/1.1" 200 0
INFO 2023-08-31 15:40:49,215 basehttp 161 "GET /usernames/daguo01/count/ HTTP/1.1" 200 39
INFO 2023-08-31 15:40:49,218 basehttp 161 "GET /mobiles/18211111111/count/ HTTP/1.1" 200 39
INFO 2023-08-31 15:40:49,388 basehttp 161 "POST /register/ HTTP/1.1" 200 27
WARNING 2023-08-31 15:40:49,843 log 224 Not Found: /carts/simple/
WARNING 2023-08-31 15:40:49,844 basehttp 161 "GET /carts/simple/ HTTP/1.1" 404 2540
INFO 2023-08-31 15:56:19,432 autoreload 636 Watching for file changes with StatReloader
INFO 2023-08-31 15:56:25,579 basehttp 161 "GET /usernames/daguo02/count/ HTTP/1.1" 200 39
INFO 2023-08-31 15:56:34,458 basehttp 161 "GET /mobiles/18211111112/count/ HTTP/1.1" 200 39
INFO 2023-08-31 15:56:37,309 basehttp 161 "GET /usernames/daguo02/count/ HTTP/1.1" 200 39
INFO 2023-08-31 15:56:37,311 basehttp 161 "GET /mobiles/18211111112/count/ HTTP/1.1" 200 39
INFO 2023-08-31 15:56:37,466 basehttp 161 "POST /register/ HTTP/1.1" 200 27
WARNING 2023-08-31 15:56:37,690 log 224 Not Found: /carts/simple/
WARNING 2023-08-31 15:56:37,690 basehttp 161 "GET /carts/simple/ HTTP/1.1" 404 2540
INFO 2023-08-31 22:41:20,155 autoreload 668 Watching for file changes with StatReloader
INFO 2023-08-31 22:41:21,661 basehttp 212 "GET /image_code/123/ HTTP/1.1" 200 3017
INFO 2023-08-31 22:41:29,910 basehttp 212 "GET /image_code/123 HTTP/1.1" 301 0
WARNING 2023-08-31 22:41:33,461 log 241 Not Found: /
WARNING 2023-08-31 22:41:33,461 basehttp 212 "GET / HTTP/1.1" 404 2769
WARNING 2023-08-31 22:41:42,828 log 241 Not Found: /carts/simple/
WARNING 2023-08-31 22:41:42,829 basehttp 212 "GET /carts/simple/ HTTP/1.1" 404 2826
WARNING 2023-08-31 22:41:44,381 log 241 Not Found: /image_codes/9c485cc1-98f8-4e90-a01e-52943b1e2775/
WARNING 2023-08-31 22:41:44,381 basehttp 212 "GET /image_codes/9c485cc1-98f8-4e90-a01e-52943b1e2775/ HTTP/1.1" 404 2934
WARNING 2023-08-31 22:41:46,611 log 241 Not Found: /image_codes/21a0c0e6-34d8-4abe-83e9-092eb2f64df9/
WARNING 2023-08-31 22:41:46,611 basehttp 212 "GET /image_codes/21a0c0e6-34d8-4abe-83e9-092eb2f64df9/ HTTP/1.1" 404 2934
WARNING 2023-08-31 22:41:47,136 log 241 Not Found: /image_codes/cd33c963-7de8-4ccd-9cc9-b70041b9e481/
WARNING 2023-08-31 22:41:47,136 basehttp 212 "GET /image_codes/cd33c963-7de8-4ccd-9cc9-b70041b9e481/ HTTP/1.1" 404 2934
WARNING 2023-08-31 22:41:47,306 log 241 Not Found: /image_codes/4f752b5b-355c-4014-a84c-d00e1914a67d/
WARNING 2023-08-31 22:41:47,306 basehttp 212 "GET /image_codes/4f752b5b-355c-4014-a84c-d00e1914a67d/ HTTP/1.1" 404 2934
WARNING 2023-08-31 22:41:47,557 log 241 Not Found: /image_codes/283c6a2b-06d6-470d-9818-4c3b0d4b66b7/
WARNING 2023-08-31 22:41:47,558 basehttp 212 "GET /image_codes/283c6a2b-06d6-470d-9818-4c3b0d4b66b7/ HTTP/1.1" 404 2934
WARNING 2023-08-31 22:41:47,740 log 241 Not Found: /image_codes/b4e1556a-fb91-4f7c-b8cf-9ee25ca598e0/
WARNING 2023-08-31 22:41:47,741 basehttp 212 "GET /image_codes/b4e1556a-fb91-4f7c-b8cf-9ee25ca598e0/ HTTP/1.1" 404 2934
WARNING 2023-08-31 22:41:47,914 log 241 Not Found: /image_codes/395636f4-fc27-4eba-b850-ce220b30aea0/
WARNING 2023-08-31 22:41:47,915 basehttp 212 "GET /image_codes/395636f4-fc27-4eba-b850-ce220b30aea0/ HTTP/1.1" 404 2934
WARNING 2023-08-31 22:41:48,099 log 241 Not Found: /image_codes/3bebc005-15b5-4fe1-91cf-45f0d3ef2e29/
WARNING 2023-08-31 22:41:48,099 basehttp 212 "GET /image_codes/3bebc005-15b5-4fe1-91cf-45f0d3ef2e29/ HTTP/1.1" 404 2934
WARNING 2023-08-31 22:41:48,279 log 241 Not Found: /image_codes/a3644ad2-24ba-4bd7-a623-79a3a27b6091/
WARNING 2023-08-31 22:41:48,280 basehttp 212 "GET /image_codes/a3644ad2-24ba-4bd7-a623-79a3a27b6091/ HTTP/1.1" 404 2934
WARNING 2023-08-31 22:41:48,466 log 241 Not Found: /image_codes/0e3f328e-db75-4553-8316-2ca3d1a2935f/
WARNING 2023-08-31 22:41:48,466 basehttp 212 "GET /image_codes/0e3f328e-db75-4553-8316-2ca3d1a2935f/ HTTP/1.1" 404 2934
WARNING 2023-08-31 22:41:48,636 log 241 Not Found: /image_codes/c457b1c0-d959-4036-bd16-d4294821e7fe/
WARNING 2023-08-31 22:41:48,637 basehttp 212 "GET /image_codes/c457b1c0-d959-4036-bd16-d4294821e7fe/ HTTP/1.1" 404 2934
WARNING 2023-08-31 22:41:49,649 log 241 Not Found: /image_codes/b98450fe-04da-4132-9943-635423b0b19d/
WARNING 2023-08-31 22:41:49,650 basehttp 212 "GET /image_codes/b98450fe-04da-4132-9943-635423b0b19d/ HTTP/1.1" 404 2934
WARNING 2023-08-31 22:41:50,012 log 241 Not Found: /image_codes/0c34dd70-0150-4789-919c-4485fde90123/
WARNING 2023-08-31 22:41:50,012 basehttp 212 "GET /image_codes/0c34dd70-0150-4789-919c-4485fde90123/ HTTP/1.1" 404 2934
INFO 2023-08-31 22:44:50,841 autoreload 266 E:\PythonProject\meiduo_project\meiduo_mall\apps\verifications\urls.py changed, reloading.
INFO 2023-08-31 22:44:51,611 autoreload 668 Watching for file changes with StatReloader
WARNING 2023-08-31 22:46:46,852 log 241 Not Found: /carts/simple/
WARNING 2023-08-31 22:46:46,853 basehttp 212 "GET /carts/simple/ HTTP/1.1" 404 2827
INFO 2023-08-31 22:46:58,489 basehttp 212 "GET /image_codes/1f58ae9d-2a94-4d23-8ccf-29276c3f4af6/ HTTP/1.1" 200 3525
INFO 2023-08-31 22:46:59,501 basehttp 212 "GET /image_codes/35cdef94-80ef-4bd8-a102-b6f03fcb006e/ HTTP/1.1" 200 3198
INFO 2023-08-31 22:47:00,431 basehttp 212 "GET /image_codes/7753d6a5-b3ce-4d0f-80f5-d7d8e2686df2/ HTTP/1.1" 200 3378
INFO 2023-08-31 22:47:01,174 basehttp 212 "GET /image_codes/5d2fe9b1-f699-4dec-afda-87e53d11fc49/ HTTP/1.1" 200 3088
INFO 2023-08-31 22:47:01,672 basehttp 212 "GET /image_codes/9c9624e5-2ba3-42b5-9bcf-bee5c175e8ae/ HTTP/1.1" 200 3473
INFO 2023-08-31 22:47:02,057 basehttp 212 "GET /image_codes/8b46e022-bb35-4d49-82a9-c8a19f0e5160/ HTTP/1.1" 200 3362
INFO 2023-08-31 22:47:02,345 basehttp 212 "GET /image_codes/44491154-daf7-44b4-93ee-cd3bc3c1cd17/ HTTP/1.1" 200 3291
INFO 2023-08-31 22:47:02,713 basehttp 212 "GET /image_codes/c7947e93-ad8a-4684-9e45-ef22742d6190/ HTTP/1.1" 200 3405
INFO 2023-08-31 22:47:03,003 basehttp 212 "GET /image_codes/c6d79bb5-532c-4926-b91c-97a33ada95a8/ HTTP/1.1" 200 3734
INFO 2023-08-31 22:47:03,176 basehttp 212 "GET /image_codes/479ba78b-9ef3-4511-9345-ec2738f03abf/ HTTP/1.1" 200 3263
INFO 2023-08-31 22:47:03,340 basehttp 212 "GET /image_codes/4808eda4-ce4c-4f05-b1d5-506277515de4/ HTTP/1.1" 200 3369
INFO 2023-08-31 22:47:03,510 basehttp 212 "GET /image_codes/2bfaef6b-890a-42e0-a18a-24a1f7edd7bc/ HTTP/1.1" 200 2866
INFO 2023-08-31 22:56:30,185 autoreload 668 Watching for file changes with StatReloader
INFO 2023-08-31 22:56:35,551 basehttp 212 "GET /image_codes/3886ce15-cb39-4175-b3d7-c800c3c1dbfe/ HTTP/1.1" 200 3222
INFO 2023-08-31 22:56:36,686 basehttp 212 "GET /image_codes/11fbd4af-9409-46fa-931d-337530d7ef90/ HTTP/1.1" 200 3159
INFO 2023-08-31 22:56:37,543 basehttp 212 "GET /image_codes/235ad0b4-bf31-4604-a45f-ebe0f5b4660c/ HTTP/1.1" 200 2880
INFO 2023-08-31 22:56:37,711 basehttp 212 "GET /image_codes/1357fc23-e497-438d-8370-2d58e28184ce/ HTTP/1.1" 200 2854
INFO 2023-08-31 22:56:37,857 basehttp 212 "GET /image_codes/868724a6-5812-40a3-80bb-96a272c8343b/ HTTP/1.1" 200 3468
INFO 2023-08-31 22:56:38,013 basehttp 212 "GET /image_codes/b4f90d46-a4b3-445f-8473-dcf0527f4597/ HTTP/1.1" 200 3323
INFO 2023-08-31 22:56:38,315 basehttp 212 "GET /image_codes/f6a9c866-0342-4b71-8284-f414ea7918df/ HTTP/1.1" 200 3310
INFO 2023-08-31 22:56:38,474 basehttp 212 "GET /image_codes/4d6c46e1-1995-4d4e-9f69-94c7c5b28328/ HTTP/1.1" 200 3516
INFO 2023-08-31 22:56:38,604 basehttp 212 "GET /image_codes/adcdbae2-4511-4827-9746-1d57d58d0027/ HTTP/1.1" 200 3069
INFO 2023-08-31 22:56:38,766 basehttp 212 "GET /image_codes/f186cb1f-ee55-436e-b187-38affc6e9fad/ HTTP/1.1" 200 3314
INFO 2023-08-31 22:56:38,918 basehttp 212 "GET /image_codes/3c3d4841-153b-4651-b7e5-4ecc2b40bd42/ HTTP/1.1" 200 3432
INFO 2023-08-31 22:56:39,093 basehttp 212 "GET /image_codes/1232b25d-4ac4-49f0-80e6-1fc1c140d42b/ HTTP/1.1" 200 3631
INFO 2023-08-31 22:56:39,256 basehttp 212 "GET /image_codes/6a048bec-4e83-4190-88f2-027d5e421420/ HTTP/1.1" 200 3425
INFO 2023-08-31 22:56:39,406 basehttp 212 "GET /image_codes/4e097c43-1d34-41d2-a639-b2ecbb3fb5e7/ HTTP/1.1" 200 3289
INFO 2023-08-31 22:56:39,558 basehttp 212 "GET /image_codes/2fa09686-7427-4464-a03a-9066e6ddd39e/ HTTP/1.1" 200 3164
INFO 2023-08-31 22:56:39,709 basehttp 212 "GET /image_codes/4fd42c72-23e0-488e-b893-7433c8409e74/ HTTP/1.1" 200 3319
INFO 2023-08-31 22:56:39,881 basehttp 212 "GET /image_codes/380936b9-6449-4f5a-a863-15591a2bd7a0/ HTTP/1.1" 200 3049
